export const animesSeason = [
  {
    mal_id: 41930,
    url: "https://myanimelist.net/anime/41930/Kamisama_ni_Natta_Hi",
    title: "Kamisama ni Natta Hi",
    image_url: "https://cdn.myanimelist.net/images/anime/1564/108648.jpg",
    members: 31948,
    genres: [
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 10,
        type: "anime",
        name: "Fantasy",
        url: "https://myanimelist.net/anime/genre/10/Fantasy",
      },
    ],
    source: "Original",
    producers: [
      {
        mal_id: 132,
        type: "anime",
        name: "P.A. Works",
        url: "https://myanimelist.net/anime/producer/132/PA_Works",
      },
    ],
    score: {},
    licensors: [],
    r18: false,
    kids: false,
    continuing: false,
  },
  {
    mal_id: 40595,
    url:
      "https://myanimelist.net/anime/40595/Kimi_to_Boku_no_Saigo_no_Senjou_Aruiwa_Sekai_ga_Hajimaru_Seisen",
    title: "Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen",
    image_url: "https://cdn.myanimelist.net/images/anime/1100/109044.jpg",
    members: 27027,
    genres: [
      {
        mal_id: 1,
        type: "anime",
        name: "Action",
        url: "https://myanimelist.net/anime/genre/1/Action",
      },
      {
        mal_id: 38,
        type: "anime",
        name: "Military",
        url: "https://myanimelist.net/anime/genre/38/Military",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
      {
        mal_id: 10,
        type: "anime",
        name: "Fantasy",
        url: "https://myanimelist.net/anime/genre/10/Fantasy",
      },
    ],
    source: "Light novel",
    producers: [
      {
        mal_id: 300,
        type: "anime",
        name: "Silver Link.",
        url: "https://myanimelist.net/anime/producer/300/Silver_Link",
      },
    ],
    score: {},
    licensors: ["Funimation"],
    r18: false,
    kids: false,
    continuing: false,
  },
  {
    mal_id: 40059,
    url: "https://myanimelist.net/anime/40059/Golden_Kamuy_3rd_Season",
    title: "Golden Kamuy 3rd Season",
    image_url: "https://cdn.myanimelist.net/images/anime/1763/108108.jpg",
    synopsis: "Third season of Golden Kamuy.",
    type: "TV",
    airing_start: "2020-10-05T14:00:00+00:00",
    episodes: {},
    members: 26763,
    genres: [
      {
        mal_id: 1,
        type: "anime",
        name: "Action",
        url: "https://myanimelist.net/anime/genre/1/Action",
      },
      {
        mal_id: 2,
        type: "anime",
        name: "Adventure",
        url: "https://myanimelist.net/anime/genre/2/Adventure",
      },
      {
        mal_id: 4,
        type: "anime",
        name: "Comedy",
        url: "https://myanimelist.net/anime/genre/4/Comedy",
      },
      {
        mal_id: 13,
        type: "anime",
        name: "Historical",
        url: "https://myanimelist.net/anime/genre/13/Historical",
      },
      {
        mal_id: 42,
        type: "anime",
        name: "Seinen",
        url: "https://myanimelist.net/anime/genre/42/Seinen",
      },
    ],
    source: "Manga",
    producers: [
      {
        mal_id: 1393,
        type: "anime",
        name: "Geno Studio",
        url: "https://myanimelist.net/anime/producer/1393/Geno_Studio",
      },
    ],
    score: {},
    licensors: [],
    r18: false,
    kids: false,
    continuing: false,
  },
  {
    mal_id: 40454,
    url:
      "https://myanimelist.net/anime/40454/Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_III",
    title: "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III",
    image_url: "https://cdn.myanimelist.net/images/anime/1523/108380.jpg",
    synopsis:
      "Third season of Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka.",
    type: "TV",
    airing_start: "2020-10-02T15:30:00+00:00",
    episodes: {},
    members: 120510,
    genres: [
      {
        mal_id: 1,
        type: "anime",
        name: "Action",
        url: "https://myanimelist.net/anime/genre/1/Action",
      },
      {
        mal_id: 2,
        type: "anime",
        name: "Adventure",
        url: "https://myanimelist.net/anime/genre/2/Adventure",
      },
      {
        mal_id: 4,
        type: "anime",
        name: "Comedy",
        url: "https://myanimelist.net/anime/genre/4/Comedy",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
      {
        mal_id: 10,
        type: "anime",
        name: "Fantasy",
        url: "https://myanimelist.net/anime/genre/10/Fantasy",
      },
    ],
    source: "Light novel",
    producers: [
      {
        mal_id: 7,
        type: "anime",
        name: "J.C.Staff",
        url: "https://myanimelist.net/anime/producer/7/JCStaff",
      },
    ],
    score: {},
    licensors: [],
    r18: false,
    kids: false,
    continuing: false,
  },
  {
    mal_id: 40776,
    url: "https://myanimelist.net/anime/40776/Haikyuu__To_the_Top_2nd_Season",
    title: "Haikyuu!!: To the Top 2nd Season",
    image_url: "https://cdn.myanimelist.net/images/anime/1453/106768.jpg",
    synopsis: "Second half of Haikyuu!!: To the Top.",
    type: "TV",
    airing_start: "2020-10-02T17:25:00+00:00",
    episodes: 12,
    members: 109643,
    genres: [
      {
        mal_id: 4,
        type: "anime",
        name: "Comedy",
        url: "https://myanimelist.net/anime/genre/4/Comedy",
      },
      {
        mal_id: 30,
        type: "anime",
        name: "Sports",
        url: "https://myanimelist.net/anime/genre/30/Sports",
      },
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 23,
        type: "anime",
        name: "School",
        url: "https://myanimelist.net/anime/genre/23/School",
      },
      {
        mal_id: 27,
        type: "anime",
        name: "Shounen",
        url: "https://myanimelist.net/anime/genre/27/Shounen",
      },
    ],
    source: "Manga",
    producers: [
      {
        mal_id: 10,
        type: "anime",
        name: "Production I.G",
        url: "https://myanimelist.net/anime/producer/10/Production_IG",
      },
    ],
    score: {},
    licensors: [],
    r18: false,
    kids: false,
    continuing: false,
  },
  {
    mal_id: 40497,
    url:
      "https://myanimelist.net/anime/40497/Mahouka_Koukou_no_Rettousei__Raihousha-hen",
    title: "Mahouka Koukou no Rettousei: Raihousha-hen",
    image_url: "https://cdn.myanimelist.net/images/anime/1788/106668.jpg",
    type: "TV",
    airing_start: "2020-10-03T15:30:00+00:00",
    episodes: {},
    members: 76768,
    genres: [
      {
        mal_id: 1,
        type: "anime",
        name: "Action",
        url: "https://myanimelist.net/anime/genre/1/Action",
      },
      {
        mal_id: 24,
        type: "anime",
        name: "Sci-Fi",
        url: "https://myanimelist.net/anime/genre/24/Sci-Fi",
      },
      {
        mal_id: 37,
        type: "anime",
        name: "Supernatural",
        url: "https://myanimelist.net/anime/genre/37/Supernatural",
      },
      {
        mal_id: 16,
        type: "anime",
        name: "Magic",
        url: "https://myanimelist.net/anime/genre/16/Magic",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
      {
        mal_id: 23,
        type: "anime",
        name: "School",
        url: "https://myanimelist.net/anime/genre/23/School",
      },
    ],
    source: "Light novel",
    producers: [
      {
        mal_id: 441,
        type: "anime",
        name: "8bit",
        url: "https://myanimelist.net/anime/producer/441/8bit",
      },
    ],
    score: {},
    licensors: [],
    r18: false,
    kids: false,
    continuing: false,
  },
];
