export const SEARCH_ANIMES = "SEARCH_ANIMES";
export const GET_ANIME_AND_CHARACTERS = "GET_ANIME_AND_CHARACTERS";
export const GET_SEASONAL_ANIME = "GET_SEASONAL_ANIME";
export const CLEAR_ANIMES = "CLEAR_ANIMES";
export const SET_LOADING = "SET_LOADING";

export const GET_TOP_ANIME = "GET_TOP_ANIME";
export const GET_TOP_ANIME_MOVIE = "GET_TOP_ANIME_MOVIE";
export const GET_TOP_MANGA = "GET_TOP_MANGA";
export const GET_TOP_NOVEL = "GET_TOP_NOVEL";
export const GET_TOP_MANHWA = "GET_TOP_MANHWA";

export const GET_SEASON = "GET_SEASON";
